name: obd_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_modular: ^5.0.0
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  http: any
  dio: ^4.0.6
  dialog_flowtter:
  mask_text_input_formatter: ^2.1.0
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - ./lib/assets/
    - ./lib/assets/i18n/
    - ./lib/assets/images/
    - ./lib/assets/images/car_obd.svg
    - ./lib/assets/images/locker.svg
    - ./lib/assets/dialog_flow_auth.json
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-Regular.ttf
          style: normal
          weight: 400
        - asset: lib/assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 700
        - asset: lib/assets/fonts/Inter/Inter-Bold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter/Inter-Thin.ttf
          weight: 100


